language: c
dist: xenial
addons:
  apt:
    packages:
    - autoconf 
    - automake 
    - autotools-dev 
    - bc 
    - bison 
    - build-essential 
    - curl 
    - expat 
    - libexpat-dev1 
    - flex 
    - gawk
    - gcc
    - git
    - gperf
    - libgmp-dev
    - libmpc-dev
    - libmpfr-dev 
    - libtool
    - texinfo
    - tmux
    - patchutils
    - zlib1g-dev
    - wget
    - bzip2
    - patch
    - vim-common
    - lbzip2
    - python
    - pkg-config
    - libglib2.0-dev
    - libpixman-1-dev
branches:
  only:
    - travis

script: ./scripts/travis.sh
