language: c
dist: xenial
cache:
  apt: true
  directories:
    - riscv
    - riscv-gnu-toolchain
git:
  submodules: false

addons:
  apt:
    packages:
    - autoconf 
    - automake 
    - autotools-dev 
    - bc 
    - bison 
    - build-essential 
    - curl 
    - expat 
    - libexpat-dev 
    - flex 
    - gawk
    - gcc
    - git
    - gperf
    - libgmp-dev
    - libmpc-dev
    - libmpfr-dev 
    - libtool
    - texinfo
    - tmux
    - patchutils
    - zlib1g-dev
    - wget
    - bzip2
    - patch
    - vim-common
    - lbzip2
    - python
    - pkg-config
    - libglib2.0-dev
    - libpixman-1-dev
branches:
  only:
    - travis

before_install:
  - travis_wait 120 git submodule update --init --recursive

script: 
	- mkdir riscv
	- export RISCV=$(pwd)/riscv
	- export PATH=$PATH:$RISCV/bin
	- cd riscv-gnu-toolchain
	- ./configure --prefix=$RISCV
	- make && make linux
	- cd ..
	- source source.sh 
	- cd busybear-linux
	- make
	- cd ..
	- ./scripts/apply-patch.sh
	- cd riscv-qemu
	- ./configure --target-list=riscv64-softmmu,riscv32-softmmu
	- make
	- cd ..
	- cd riscv-linux
	- cp ../busybear-linux/conf/linux.config .config
	- make ARCH=riscv olddefconfig
	- make ARCH=riscv vmlinux
	- cd ..
	- cd riscv-pk
	- mkdir build
	- cd build
	- ../configure --enable-logo --host=riscv64-unknown-elf --with-payload=../../riscv-linux/vmlinux --enable-sm
	- make
	- cd bootrom
	- make
	- cd ..
	- cd sdk
	- make
	- make copy-tests
	- cd ..
